apiVersion: v1
kind: Service
metadata:
  name: appsmith-service
  namespace: appsmith
spec:
  selector:
    app: appsmith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 
