apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsmith-deployment
  namespace: appsmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsmith
  template:
    metadata:
      labels:
        app: appsmith
    spec:
      containers:
        - name: appsmith
          image: index.docker.io/appsmith/appsmith-ce
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo-service:27017/appsmith"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
          volumeMounts:
            - name: appsmith-config
              mountPath: /appsmith/config
      volumes:
        - name: appsmith-config
          configMap:
            name: appsmith-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appsmith-config
data:
