apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: appsmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.10-focal
          ports:
            - containerPort: 27017
